// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	model "github.com/deeraj-kumar/exam-audit/domain"
	mock "github.com/stretchr/testify/mock"
)

// FabricService is an autogenerated mock type for the FabricService type
type FabricService struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *FabricService) Close() {
	_m.Called()
}

// QueryEdittedAnswersByExam provides a mock function with given fields: exam, students
func (_m *FabricService) QueryEdittedAnswersByExam(exam model.Exam, students []model.Student) ([]model.Answer, error) {
	ret := _m.Called(exam, students)

	if len(ret) == 0 {
		panic("no return value specified for QueryEdittedAnswersByExam")
	}

	var r0 []model.Answer
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Exam, []model.Student) ([]model.Answer, error)); ok {
		return rf(exam, students)
	}
	if rf, ok := ret.Get(0).(func(model.Exam, []model.Student) []model.Answer); ok {
		r0 = rf(exam, students)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Answer)
		}
	}

	if rf, ok := ret.Get(1).(func(model.Exam, []model.Student) error); ok {
		r1 = rf(exam, students)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetAnswer provides a mock function with given fields: studentId, examID, questionID, ans
func (_m *FabricService) SetAnswer(studentId string, examID string, questionID string, ans string) error {
	ret := _m.Called(studentId, examID, questionID, ans)

	if len(ret) == 0 {
		panic("no return value specified for SetAnswer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) error); ok {
		r0 = rf(studentId, examID, questionID, ans)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewFabricService creates a new instance of FabricService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFabricService(t interface {
	mock.TestingT
	Cleanup(func())
}) *FabricService {
	mock := &FabricService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
